flow:
  whoami: true
  visit: true

# faucet
visitEvent:
  type: game:visitValidatorHouse
  payload: {}

claim:
  spam: 1
  intervalMs: 2500
  maxAttempts: 6
  baseDelayMs: 1000
  maxDelayMs: 8000

events:
  sendClaimEvent: true

log:
  level: silent            # info | debug | silent
  maxBodyChars: 180
  elideHtml: true
  showHeaders: false

# Balance 
balances:
  networks:
    - name: Neura Testnet
      rpcEnv: NEURA_RPC
      rpc: null
      nativeSymbol: ANKR
      erc20:
        symbol: WANKR
        address: "0xbd833b6ecc30caeabf81db18bb0f1e00c6997e7a"
        decimals: 18
  # token opsional sepolia (ERC20)
  sepoliaToken:
    symbol: ANKR
    address: "0xB88Ca91Fef0874828e5ea830402e9089aaE0bB7F"
    decimals: 18

#  Bridge setting 
bridge:
  visitEvent:
    type: bridge:visit
    payload: {}

  token:
    symbol: ANKR
    address: "0xB88Ca91Fef0874828e5ea830402e9089aaE0bB7F"   
    decimals: 18
  spender: "0xC6255a594299f1776De376D0509AB5AB875A6E3E"    
  amount: "1.0"            # need to bridge / amount
  recipient: "$OWNER"      
  waitForReceipt: true
  confirmations: 1
  pollMs: 2500

# SWAP Settings 
swap:
  pools:
    - "0xfd9741523af12334c855635e883c886214276f6d"   
    - ""  

  tokenIn:
    symbol: WANKR
    address: "0xBd833b6eCC30CAEaBf81dB18BB0f1e00C6997E7a"
    decimals: 18
  tokenOut:
    symbol: 
    address: "0x9423c6c914857e6daaace3b585f4640231505128"
    decimals: 6

  amountIn: "0.1"          # need to swap
  slippageBps: 100          # 1%
  poolFee: 500             
  waitForReceipt: true
  confirmations: 1


