ui:
  enabled: true          # aktifkan TUI
  panels: 12              # 4 kotak (2x2). Bisa 6 (3x2) atau 9 (3x3)
  maxPerPanel: 12        # maksimal 10 akun per kotak
  timestamp: false
  sessionBar: true       # aktifkan 1 panel SESSION global (login/expiry/relogin)
  sessionHeightPct: 22   # tinggi SESSION bar (persen)
  compactSwapLogs: true   # ringkas log swap
  compactTaskLogs: true   # ringkas log task
  strictCompact: true     # <— drop semua yang tidak masuk allowlist
  maxLinesPerPanel: 120   # batasi jumlah baris per panel
  truncateWidth: 200       # potong panjang setiap baris
  muteRpcErrors: true
  disableTicker: false  # biar ada interval yg bikin proses tetap hidup


auth:
  loginTries: 5      # jumlah percobaan login awal
  minGapMs: 9000
  rateBaseMs: 4000
  rateBackoff: 1.8
  rateJitterMs: 500
  loginStaggerMs: 1000      # jeda antar login (ms)
  loginConcurrency: 5
keepAlive:
  renewSkewMs: 900000
  idleOnly: true   # hidupkan mode idle
  hours: 24        # tahan 24 jam
  sleepMs: 300000  # jeda antar ping (5 menit)
  ping:
    enabled: true

authGuard:
  checkMs: 120000
  jitterMs: 15000
  staggerMs: 3000
  maxFails: 3
  coolOffMs: 1800000

flow:
  loginBatchSize:
  perAccountMax: 12
  maxConcurrency: 12
  batchPasses: 2           # berapa PASS rebatch (coba lagi) sebelum skip permanen
  betweenBatchesMs: 4000   # jeda antar batch
  repeatRounds: true
  idleMs: 3000
  betweenAccountsMs: 0
  mode: grouped
  parallelGroups:
    - [game, collect]
    - [faucet]
    - [bridge]
    - [swap]
    - [task]
  order: [game, faucet, swap, task, swap, swap, task]

  afterAll:
    enabled: false  #nonaktif kalau aktife = true
    modules: [swap]                # modul akhir untuk SEMUA akun
    concurrency: 4
    rounds: 5
    delayBetweenModulesMs: 1500
    delayBetweenRoundsMs: 5000

log:
  level: silent          # biar panel gak kebanjiran; pakai debugapi kalau perlu
  socketLevel: on
  showHeaders: false
  maxBodyChars: 180
  elideHtml: true

visitEvent:
  type: game:visitValidatorHouse
  payload: {}

claim:
  skipIfBelowPoints: true
  minPoints: 50
  preferBodyKeys: [to, address, recipient, walletAddress, wallet, "{}"]

  retryForever: false
  attempts: 5
  factor: 1.6
  jitterMs: 80

  spam: 20
  intervalMs: 25

  maxAttempts: 6
  baseDelayMs: 1000
  maxDelayMs: 8000

  stopOn:
    - already received
    - already claimed
    - cooldown
    - insufficient neurapoints
    - need at least
    - points to claim

events:
  sendClaimEvent: true

net:
  timeoutMs: 45000
  retries: 4
  baseDelayMs: 300
  backoff: 1.8
  jitterMs: 200

login:
  tries: 3

balances:
  networks:
    - name: Neura Testnet
      rpcEnv: NEURA_RPC
      rpc: null
      nativeSymbol: ANKR
      erc20:
        symbol: WANKR
        address: "0xbd833b6ecc30caeabf81db18bb0f1e00c6997e7a"
        decimals: 18
  sepoliaToken:
    symbol: ANKR
    address: "0xB88Ca91Fef0874828e5ea830402e9089aaE0bB7F"
    decimals: 18

bridge:
  visitEvent:
    type: bridge:visit
    payload: {}
  token:
    symbol: ANKR
    address: "0xB88Ca91Fef0874828e5ea830402e9089aaE0bB7F"
    decimals: 18
  spender: "0xC6255a594299f1776De376D0509AB5AB875A6E3E"
  amount: "1.0"
  recipient: "$OWNER"
  waitForReceipt: true
  confirmations: 1
  pollMs: 2500

game:
  maxPulseSearch: 7
  perLocationRetry:
    attempts: 2
    baseDelayMs: 1
    backoff: 1.6
    jitterMs: 1
  visitDelayMs: 3
  visits:
    - { type: "game:visitFountain",        payload: {} }
    - { type: "game:visitOracle",          payload: {} }
    - { type: "game:visitBridge",          payload: {} }
    - { type: "game:visitObservationDeck", payload: {} }
    - { type: "game:visitValidatorHouse",  payload: {} }

collect:
  mode: scan
  attempts: 2
  factor: 1.0
  jitterMs: 100
  burst:
    count: 8
    intervalMs: 50
  stopOn:
    - already received
    - already collected
    - cooldown
    - invalid pulse

swap:
  minNativeForFee: "0.2"
  autoback: true
  autobackCycles: 5
  useRouter: "wankr/ztusd,ztusd/wankr"
  strictAOnly: true
  disallowForceSend: true
  resimulateBeforeSend: true
  retry:
    attempts: 3       # berapa kali dicoba
    delayMs: 10000    # jeda antar percobaan (default 10 detik)
    backoff: 1.0      # 1.0 = tetap; >1.0 = bertambah tiap retry
    jitterMs: 250     # opsional: jitter +- ms
    tries: 6
    base: 100

  rpcRetry:
    tries: 6
    base: 600
    backoff: 1.9
    jitter: 250
    pollMs: 4000
    totalMs: 300000

  feeTopup:
    enabled: true
    minNative: "0.1"
    buffer: "0.03"
    maxTries: 3
    preferRouteBack: "ztusd/wankr"

  routes:
    - name: "wankr/ztusd"
      amount: "max"                  # max = semua saldo WANKR
      router: "0x5AeFBA317BAba46EAF98Fd6f381d07673bcA6467"
      wrapFirst: true                  # boleh boolean true (tanpa quotes)
      wtoken: "0xbd833b6ecc30caeabf81db18bb0f1e00c6997e7a"   # WANKR (kontrak wrap)
      value:  "max"    # 1 ANKR yang akan di-wrap ke WANKR
      calldata: "0x1679c792000000000000000000000000bd833b6ecc30caeabf81db18bb0f1e00c6997e7a0000000000000000000000009423c6c914857e6daaace3b585f464023150512800000000000000000000000000000000000000000000000000000000000000000000000000000000000000005515d2311d2edb6e24a4dff0c8299cb7a7994f9f00000000000000000000000000000000000000000000000000000199ebde92090000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000bf5d0000000000000000000000000000000000000000000000000000000000000000"
      tokenIn:  "0xbd833b6ecc30caeabf81db18bb0f1e00c6997e7a"   # WANKR (hasil wrap)
      tokenOut: "0x9423c6c914857e6daaace3b585f4640231505128"   # ztUSD
      times: 5

      patches:
        - mode: findExact
          old: "0x5515d2311d2EDb6e24a4dfF0C8299cB7a7994f9F"
          to: "$OWNER"
        - mode: auto
          index: 13
      gas:
        addPercent: 10
        limitBumpPercent: 25
        limitAdd: 30000


    - name: "ztusd/wankr"
      amount: "max" 
      router: "0x5AeFBA317BAba46EAF98Fd6f381d07673bcA6467"
      calldata: "0x1679c7920000000000000000000000009423c6c914857e6daaace3b585f4640231505128000000000000000000000000bd833b6ecc30caeabf81db18bb0f1e00c6997e7a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dc91fdbf1f8e5f470788cebac7e3b13dd63bd4bc00000000000000000000000000000000000000000000000000000199ec912e99000000000000000000000000000000000000000000000000000000000000c0940000000000000000000000000000000000000000000000000dd42a8e3d0323630000000000000000000000000000000000000000000000000000000000000000"
      tokenIn:  "0x9423c6c914857e6daaace3b585f4640231505128"
      tokenOut: "0xbd833b6ecc30caeabf81db18bb0f1e00c6997e7a"
      times: 5
      dynamicFixes:
        subIndex: 0
        amountInFromBalance: true   # akan otomatis pakai sisa saldo ztUSD
        minOutWord: 11
        hardcodeMinOut: "0"
      patches:
        - mode: findExact
          old: "0xdC91FDbf1f8e5F470788CeBaC7e3B13DD63bD4bc"
          to: "$OWNER"
        - mode: auto
          index: 13

      gas:
        addPercent: 10
        limitBumpPercent: 25
        limitAdd: 30000
